version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:22.6.0-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run UI tests (headless)
          command: npm run test:ui -- --env chrome
      - store_artifacts:
          path: reports/ui
          destination: ui-test-reports

  api-tests:
    docker:
      - image: cimg/node:22.6.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run API tests
          command: npm run test:api
      - store_artifacts:
          path: reports/api
          destination: api-test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
